---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: spring-petclinic
spec:
  rules:
    - host: petclinic.info
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080

